import { requireStaffSession } from '@/lib/admin/auth';
import { loadCommunicationsData } from '@/lib/admin/overview-data';

export const dynamic = 'force-dynamic';
const eventLabels: Record<string, string> = { reservation_confirmation: 'Confirmación', reservation_reminder: 'Recordatorio', reservation_modification: 'Modificación', reservation_cancellation: 'Cancelación', waitlist_offer: 'Oferta de espera' };

export default async function CommunicationsPage() {
  await requireStaffSession();
  const data = await loadCommunicationsData();
  return <div className="admin-page communications-page"><div className="admin-page-head"><div><span className="admin-kicker">Outbox transaccional · auditable</span><h1>Cada mensaje tiene un motivo y un estado.</h1><p>Eventos preparados automáticamente desde reservas y lista de espera, sin mezclar marketing con operación.</p></div><span className="pending-tag important">Proveedor pendiente</span></div><div className="communication-metrics"><div><span>Pendientes</span><strong>{data.counts.pending}</strong></div><div><span>Enviados</span><strong>{data.counts.sent}</strong></div><div><span>Fallidos</span><strong>{data.counts.failed}</strong></div><div><span>Plantillas activas</span><strong>{data.templates.filter((template)=>template.enabled).length}</strong></div></div><div className="communications-layout"><section className="admin-panel communication-queue"><div className="panel-head"><div><span className="admin-kicker">Cola</span><h2>Actividad reciente</h2></div><span className="count-badge">{data.jobs.length}</span></div>{data.jobs.length ? <div>{data.jobs.map((job)=><article key={job.id}><div><strong>{eventLabels[job.eventKey] ?? job.eventKey}</strong><small>{job.channel} · {job.recipient}</small></div><span className={`communication-status status-${job.status}`}>{job.status}</span><time>{new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(job.scheduledFor))}</time></article>)}</div> : <div className="communication-empty"><h3>La cola está preparada.</h3><p>Los próximos eventos de reserva crearán trabajos con deduplicación y trazabilidad. Ninguno se marcarará como enviado hasta que el proveedor lo confirme.</p></div>}</section><aside className="admin-panel communication-templates"><span className="admin-kicker">Plantillas</span><h2>ES y EN</h2><div>{data.templates.map((template)=><article key={template.id}><div><strong>{eventLabels[template.eventKey] ?? template.eventKey}</strong><small>{template.locale.toUpperCase()} · {template.channel}</small></div><span>{template.enabled?'Activa':'Pausada'}</span></article>)}</div></aside></div><div className="communications-gate"><span>Hito de activación</span><p>Para enviar de verdad hace falta elegir proveedor, verificar el dominio remitente, definir la identidad de envío y probar entregabilidad. Hasta entonces, la cola permanece visible y controlada; no hay falsos positivos.</p></div></div>;
}
