-- La Bocana · compatibilidad rate limit + recarga explícita de PostgREST
create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_lookup_idx
  on public.rate_limit_events(key_hash, action, created_at desc);

create or replace function public.consume_rate_limit(
  p_key_hash text,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  delete from public.rate_limit_events where created_at < now() - interval '1 day';
  select count(*) into v_count
  from public.rate_limit_events
  where key_hash = p_key_hash
    and action = p_action
    and created_at >= now() - make_interval(secs => p_window_seconds);

  if v_count >= p_limit then
    return false;
  end if;

  insert into public.rate_limit_events(key_hash, action) values (p_key_hash, p_action);
  return true;
end;
$$;

revoke all on function public.consume_rate_limit(text,text,integer,integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text,text,integer,integer) to service_role;

notify pgrst, 'reload schema';
